services:
  postgres:
    image: postgres:16
    container_name: globalcart_postgres
    environment:
      POSTGRES_USER: globalcart
      POSTGRES_PASSWORD: globalcart
      POSTGRES_DB: globalcart
    ports:
      - "5432:5432"
    volumes:
      - globalcart_pgdata:/var/lib/postgresql/data

volumes:
  globalcart_pgdata:
